version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "babel-plugin-react-compiler"
      - dependency-name: "typedoc"
      - dependency-name: "typedoc-plugin-missing-exports"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
